### ISSUE TITLE
Doesn't work well with Mocha 4

### ISSUE THREAD

**Issue by darkwebdev** [oxala/marko-tester#24]
When using Mocha 4 instead of 3 I can't see any details about test failure.

Running
`./node_modules/.bin/markotester src --no-coverage --no-lint`

With Mocha 4:
```
nested-component
    Given specific input data
      1) should render component using default input
    When component is being built
      2) should initialize nested component with a proper state and config

0 passing (754ms)
  2 failing
```

With Mocha 3:

same as above + 
```
1) nested-component Given specific input data should render component using default input:

      AssertionError: expected '<div>component-1 <component-2 data-marko-key="nestedComponent s0" hello="world"></component-2></div>' to equal ''
      actual expected

      <div>component-1 <component-2 data-marko-key="nestedComponent s0" hello="world"></component-2></div>

      at Promise.catch.then (node_modules/marko-tester/source/testers/fixtures.js:82:36)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)

  2) nested-component When component is being built should initialize nested component with a proper state and config:
     ReferenceError: marko is not defined
      at Context.it (src/components/component-1/test/index.spec.js:8:14)
      at window.$_mod.require.render (node_modules/marko-tester/source/testers/component.js:35:11)
      at EventEmitter.<anonymous> (file://node_modules/marko-tester/static/source/marko$4.5.6/src/runtime/renderable.js:127:25)
      at invokeListener (file://node_modules/marko-tester/static/source/events-light$1.0.5/src/index.js:21:22)
      at EventEmitter.emit (file://node_modules/marko-tester/static/source/events-light$1.0.5/src/index.js:90:13)
      at AsyncVDOMBuilder.___doFinish (file://node_modules/marko-tester/static/source/marko$4.5.6/src/runtime/vdom/AsyncVDOMBuilder.js:191:25)
```

**Comment by oxala** [comment]
Not relevant anymore. No more mocha, no more lasso.
